data_process:
    dataset: "/media/beabbit/T5 EVO/bag/rosbag_/mulran/"
    config : "/home/beabbit/study_space/SGPR/SG_PR-master/data_process/config/MulRan.yaml"
    output_label: "/media/beabbit/T5 EVO/bag/rosbag_/mulran/"
    output_graph: "/media/beabbit/T5 EVO/bag/rosbag_/mulran/"
    label_topic: "/labeled_pc"
    graph_topic: "/graphs"

SG_data:
    data_name : "KAIST03"
    map_name  : "KAIST02"
    # data_name : "apollo-data"
    # map_name  : "2018-09-24"
    vis_flag  : true 
    random_number : 1
    map_match : true
    flag_180 : false
    stop_flag : false
    leaf_size : 3
    best_fitness: 15
    f2s_the: 2000
    s2t_the: 1000
    t2f_the: 50
    final_score_the : 0.2
    
fast_gicp:
    enable_gicp: false
    num_threads: 24 
    num_neighbors: 20
    max_iterations: 10

# best params
## DCC02
    # leaf_size : 3
    # best_fitness: 10
    # f2s_the: 600
    # s2t_the: 200
    # t2f_the: 50
    # final_score_the : 0
##SEU campus
    # leaf_size : 2
    # best_fitness: 10
    # f2s_the: 600
    # s2t_the: 200
    # t2f_the: 50
    # final_score_the : 0
## apollo-data
    # leaf_size : 3.5
    # best_fitness: 3.6
    # f2s_the: 2000
    # s2t_the: 1000
    # t2f_the: 150
    # final_score_the : 0.2
## apollo-data-2
    # leaf_size : 4
    # best_fitness: 5
    # f2s_the: 3000
    # s2t_the: 1500
    # t2f_the: 100
    # final_score_the : 0.2



######################### std param ##########################
# pre process
ds_size: 0.25
maximum_corner_num: 100

# key points
plane_detection_thre: 0.01
plane_merge_normal_thre: 0.2
voxel_size: 2.0
voxel_init_num: 10
proj_image_resolution: 0.5
proj_dis_min: 0
proj_dis_max: 5
corner_thre: 10

# std descriptor
descriptor_near_num: 10
descriptor_min_len: 0.5
descriptor_max_len: 50
non_max_suppression_radius: 2
std_side_resolution: 1

# candidate search
skip_near_num: 100
candidate_num: 50
sub_frame_num: 1
vertex_diff_threshold: 0.2
rough_dis_threshold: 0.03
normal_threshold: 0.2
dis_threshold: 0.3
icp_threshold: 0.4